/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include"FreeRTOS.h"
#include"FreeRTOSConfig.h"
#include"task.h"
#include"led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

struct param
{
	int led;
	int rate;
};

void vLedTask (void* pvParam)
{
	struct param *p = (struct param*)pvParam;
     int rate = p->rate;
     portTickType xLastWakepTime;
     xLastWakepTime = xTaskGetTickCount();

	while(1)
	{
		portENTER_CRITICAL();
		switch (p->led)
		        {
		        case 12:
		            led_toggle(LED_GREEN);
		            break;
		        case 13:
		            led_toggle(LED_ORANGE);
		            break;
		        case 14:
		            led_toggle(LED_RED);
		            break;
		        case 15:
		            led_toggle(LED_BLUE);
		            break;
		        default:
		            break;
		        }
		portEXIT_CRITICAL();
		vTaskDelayUntil(&xLastWakepTime,rate/portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}

int main(void)
{
	led_init(LED_GREEN);
	led_init(LED_RED);
	led_init(LED_BLUE);
	led_init(LED_ORANGE);
    struct param par_green = { .led = 12, .rate = 500 };
    struct param par_orange = { .led = 13, .rate = 300 };
    struct param par_red = { .led = 14, .rate = 700 };
    struct param par_blue = { .led = 15, .rate = 1000 };

    xTaskCreate(vLedTask, "GREEN", configMINIMAL_STACK_SIZE, &par_green, 5, NULL);
    xTaskCreate(vLedTask, "ORANGE", configMINIMAL_STACK_SIZE, &par_orange, 5, NULL);
    xTaskCreate(vLedTask, "RED", configMINIMAL_STACK_SIZE, &par_red, 5, NULL);
    xTaskCreate(vLedTask, "BLUE", configMINIMAL_STACK_SIZE, &par_blue, 5, NULL);
  vTaskStartScheduler();
  while(1);
}
